### ISSUE TITLE
Make modal with pdf text for each requirement

### ISSUE THREAD

**Issue by jp-hidalgo** [jp-hidalgo/vehicle-profile-editor#18]

**Comment by jp-hidalgo** [comment]
ya esta con dummy links, toca decidir a donde queremos que lleven, se pueden ver en https://github.com/jp-hidalgo/vehicle-profile-editor/blob/master/src/App.js desde la linea 137 (los route que tienen url)

**Comment by carlosfpardo** [comment]
Ready the chicken pero creo que faltan algunos más? Puedo meter URL para cada "here" que ponga, solo es que me diga.

**Comment by jp-hidalgo** [comment]
ya tienen los HERE que estan en el translation.json, no se donde mas faltan

**Comment by carlosfpardo** [comment]
Solo faltaba en "riskReq":  y lo puse (creo jajaj sigo aprendiendo).
