### ISSUE TITLE
Explanation for each requirement with the natural language

### ISSUE THREAD

**Issue by jp-hidalgo** [jp-hidalgo/vehicle-profile-editor#19]

**Comment by jp-hidalgo** [comment]
en los que tienen más de dos opciones (data requierement, fees and fines y space allocation) se ponen todas las opciones o la que sale en el policy recomendation?

**Comment by carlosfpardo** [comment]
Todas

**Comment by jp-hidalgo** [comment]
ya solo falta space allocation, donde pongo la explicacion de eso?

**Comment by carlosfpardo** [comment]
Ay. Yo creo que sobre la imagen abcd
