### ISSUE TITLE
Use the Image claudio sends for space alocation

### ISSUE THREAD

**Issue by jp-hidalgo** [jp-hidalgo/vehicle-profile-editor#21]

**Comment by carlosfpardo** [comment]
vea https://www.dropbox.com/sh/9vsl66gd4houqdy/AAA320bbsutkhehFFpv_8fZRa?dl=0

**Comment by jp-hidalgo** [comment]
ya quedo la imagen puesta, sigo arreglando formato para que quede arriba de los sitios de la imagen
