### ISSUE TITLE
Generate PDF

### ISSUE THREAD

**Issue by jp-hidalgo** [jp-hidalgo/vehicle-profile-editor#22]

**Comment by carlosfpardo** [comment]
Esta dejémosla por ahora así. No es crucial para esta versión de la herramienta (es más importante lo demás). Lo voy a pasar a done.

**Comment by jp-hidalgo** [comment]
faltan los links o lo dejamos sin ellos?

**Comment by carlosfpardo** [comment]
así como está dejémoslo y concentrémonos en lo que falta para que la pura plataforma funcione bien (yo hice cambios al código hace un rato que no sé si quedaron bien)
